# Generated by Django 6.0.6 on 2026-07-03 12:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chumbo_destinos', '0001_initial'),
        ('chumbo_montes', '0001_initial'),
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransacaoSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('peso_baixado_kg', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Peso baixado (kg)')),
                ('barras_baixadas', models.PositiveIntegerField(verbose_name='Barras baixadas')),
                ('data_transacao', models.DateTimeField(verbose_name='Data da transação')),
                ('grupo_liberacao', models.UUIDField(default=uuid.uuid4, verbose_name='Grupo de liberação')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='Observação')),
                ('estornada', models.BooleanField(default=False, verbose_name='Estornada')),
                ('estornada_em', models.DateTimeField(blank=True, null=True, verbose_name='Estornada em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='chumbo_destinos.destino', verbose_name='Destino')),
                ('estornada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Estornada por')),
                ('monte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saidas', to='chumbo_montes.pile', verbose_name='Monte')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.setor', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Transação de saída',
                'verbose_name_plural': 'Transações de saída',
                'ordering': ('-data_transacao', '-id'),
            },
        ),
    ]
