# Generated by Django 6.0.6 on 2026-07-02 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('chave_cor', models.CharField(choices=[('azul', 'Azul'), ('amarelo', 'Amarelo'), ('vermelho', 'Vermelho'), ('preto', 'Preto'), ('cinza', 'Cinza'), ('sem_cor', 'Sem cor'), ('verde', 'Verde'), ('branco', 'Branco')], default='sem_cor', max_length=20, verbose_name='Cor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Ligas',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
    ]
