# Generated by Django 6.0.6 on 2026-07-03 11:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chumbo_lotes', '0001_initial'),
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('peso_atual_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Peso atual (kg)')),
                ('barras_atuais', models.PositiveIntegerField(default=0, verbose_name='Barras atuais')),
                ('posicao_x', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Posição X')),
                ('posicao_y', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='Posição Y')),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('RESERVADO', 'Reservado'), ('PARCIAL', 'Parcial'), ('CONSUMIDO', 'Consumido')], default='DISPONIVEL', max_length=20, verbose_name='Status')),
                ('reservado_para', models.CharField(blank=True, default='', max_length=100, verbose_name='Reservado para')),
                ('reservado_em', models.DateTimeField(blank=True, null=True, verbose_name='Reservado em')),
                ('grupo_reserva_id', models.UUIDField(blank=True, null=True, verbose_name='Grupo de reserva')),
                ('localizacao', models.CharField(choices=[('almoxarifado', 'Almoxarifado'), ('setor', 'Setor')], default='almoxarifado', max_length=20, verbose_name='Localização')),
                ('movido_setor_em', models.DateTimeField(blank=True, null=True, verbose_name='Movido ao setor em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montes', to='chumbo_lotes.batch', verbose_name='Lote')),
                ('monte_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos', to='chumbo_montes.pile', verbose_name='Monte de origem (split)')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='montes_no_setor', to='shared.setor', verbose_name='Setor')),
                ('setor_reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='shared.setor', verbose_name='Setor da reserva')),
            ],
            options={
                'verbose_name': 'Monte',
                'verbose_name_plural': 'Montes',
                'ordering': ('posicao_y', 'posicao_x'),
            },
        ),
        migrations.CreateModel(
            name='PileEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(choices=[('RESERVA', 'Reserva'), ('CANCELAMENTO_RESERVA', 'Cancelamento de reserva'), ('BAIXA_PARCIAL', 'Baixa parcial'), ('BAIXA_TOTAL', 'Baixa total'), ('MOVIDO_PARA_SETOR', 'Movido para setor'), ('DEVOLVIDO_ALMOXARIFADO', 'Devolvido ao almoxarifado'), ('ESTORNO', 'Estorno'), ('SPLIT_CRIADO', 'Split criado'), ('CONSUMO_ALOCADO', 'Consumo alocado')], max_length=30, verbose_name='Tipo')),
                ('dados', models.JSONField(blank=True, null=True, verbose_name='Dados')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('monte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='chumbo_montes.pile', verbose_name='Monte')),
            ],
            options={
                'verbose_name': 'Evento de monte',
                'verbose_name_plural': 'Eventos de monte',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='pile',
            constraint=models.UniqueConstraint(fields=('lote', 'posicao_x', 'posicao_y'), name='unique_lote_posicao'),
        ),
    ]
