# Generated by Django 6.0.6 on 2026-07-03 11:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chumbo_ligas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('numero_lote', models.CharField(max_length=50, verbose_name='Número do lote')),
                ('data_chegada', models.DateField(verbose_name='Data de chegada')),
                ('peso_inicial_kg', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Peso inicial (kg)')),
                ('barras_iniciais', models.PositiveIntegerField(verbose_name='Barras iniciais')),
                ('colunas_grade', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Colunas da grade')),
                ('linhas_grade', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Linhas da grade')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='chumbo_ligas.liga', verbose_name='Liga')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ('-data_chegada', '-id'),
                'constraints': [models.UniqueConstraint(fields=('liga', 'numero_lote'), name='unique_liga_numero_lote')],
            },
        ),
    ]
