# Generated by Django 6.0.6 on 2026-07-03 13:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chumbo_lotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='capacidade_montes',
            field=models.PositiveIntegerField(default=50, help_text='Informativo. ~50 barras. Sem restrição.', verbose_name='Capacidade padrão por monte (barras)'),
        ),
        migrations.AddField(
            model_name='batch',
            name='peso_barra_ref_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('26.000'), help_text='Informativo. ~26 kg. Editável, sem validação rígida.', max_digits=10, verbose_name='Peso médio por barra (ref., kg)'),
        ),
    ]
